name: web_core
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  get: 4.6.5
  pdf: 3.10.1
  fluttertoast: 6.0.1
  shared_preferences: 0.5.5
  loading_animation_widget: 1.2.0+4
  dart_openai: 1.9.1
  http: 0.13.5
  dartz: 0.10.1
  fluent_ui: 4.5.1
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/images/kh/ #assets for kinetic hive project